"""Generates runs/report.md - the reproducible write-up of one full run.

Reporting rules this module enforces mechanically, so a report cannot be produced
that breaks them (§7, §11):

* ASR is never printed without task completion and false-positive rate beside it.
* Every number is labelled with the configuration that produced it.
* Nothing is averaged across configurations.
* The Layer-1 backend is named wherever Layer-1 numbers appear, because the
  shipped backend is a lexical stand-in and not an off-the-shelf guard model.
* No citation is emitted that is not in the closed set in README §11.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .audit import AuditLog
from .checkpoint.classifier import build_guard
from .corpus import load
from .eval.metrics import compute, render_table
from .eval.plots import degradation_curve, sweep_curve
from .eval.runner import run_corpus
from .eval.sweep import LEVEL_NAMES, TIER_SETS, render as render_sweep, run_sweep
from .redteam.loop import render as render_rt, run as run_redteam, save as save_rt

RUNS = Path("runs")
CONFIG_NOTES = {
    "none": "no AEGIS layer; measures whether the attack is feasible at all",
    "input_only": "in-band content classifier only; the current-generation baseline",
    "out_of_band": "manifest + provenance + trajectory invariants, no classifier",
    "full": "all layers",
}


def write_report(args) -> Path:
    RUNS.mkdir(exist_ok=True)
    guard = build_guard("heuristic")
    scenarios = load()
    by_id = {s.id: s for s in scenarios}

    audit = AuditLog(RUNS / "report.jsonl")
    runs = run_corpus(scenarios, list(CONFIG_NOTES), audit, guard=guard)
    metrics = [compute(n, rs.results, by_id) for n, rs in runs.items()]
    audit.close()

    cells = run_sweep()
    sweep_svg = sweep_curve(cells, list(TIER_SETS), LEVEL_NAMES, RUNS / "provenance_sweep.svg")

    rt = run_redteam(rounds=args.rounds, population=args.population, seed=args.seed,
                     target="input_only", guard=guard)
    save_rt(rt, RUNS / "redteam_input_only.json")
    rt_svg = degradation_curve(rt, RUNS / "redteam_input_only.svg")

    rt_full = run_redteam(rounds=args.rounds, population=args.population, seed=args.seed,
                          target="full", guard=guard)
    save_rt(rt_full, RUNS / "redteam_full.json")

    # Which layer decided each attack, for the attribution table.
    layer_rows = []
    for r in runs["full"].results:
        s = by_id[r.scenario_id]
        if s.kind != "attack":
            continue
        goal = next(o for o in r.outcomes if o.attack_goal)
        layer_rows.append((s.id, s.family, goal.layer, goal.reason))

    first, last = rt.rounds[0], rt.rounds[-1]
    m = {x.config: x for x in metrics}

    doc = f"""# AEGIS run report

Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} ·
corpus `corpus/scenarios.json` ({len(scenarios)} scenarios,
{sum(1 for s in scenarios if s.kind == 'attack')} attack /
{sum(1 for s in scenarios if s.kind == 'benign')} benign pairs) ·
red-team seed `{args.seed}`, {args.rounds} rounds, population {args.population}.

Everything below is regenerated by `python -m aegis report`. The harness is
deterministic: the same seed reproduces the same payloads and the same curves.

## What was measured

Four defense configurations over the same paired corpus:

| configuration | layers |
|---|---|
{chr(10).join(f'| `{k}` | {v} |' for k, v in CONFIG_NOTES.items())}

The Layer-1 classifier in `input_only` and `full` is `{guard.name}` — a lexical
detector shipped with this repo as a stand-in for an off-the-shelf guard model,
not a trained injection classifier. Layer-1 numbers should be read as
"a representative in-band filter", and the adapter for a real model
(`HFGuard`) is in place for anyone who wants to rerun with one.

## 1. Static evaluation — the three metrics together

```
{render_table(metrics)}
```

Read across, never down a single column. `none` shows every attack in the corpus
is feasible against an undefended agent ({m['none'].attack_success_rate:.0%} ASR).
`input_only` blocks {m['input_only'].blocked_attacks} of {m['input_only'].n_attack}
attacks on the *static* set. `out_of_band` and `full` block all
{m['full'].n_attack}, and pay {m['full'].false_positive_rate:.0%} false positives
for it — one benign scenario, `ben-a5`, discussed in §4.

### Which layer decided each attack

| scenario | family | deciding layer | why |
|---|---|---|---|
{chr(10).join(f'| `{i}` | {f} | **{l}** | {r[:96]} |' for i, f, l, r in layer_rows)}

No single layer covers the corpus. The manifest catches an ungranted capability,
provenance catches control-plane arguments lifted from untrusted content, and the
trajectory invariants catch the sequences where every individual call is legal.

## 2. Adaptive red-team loop — the headline result

```
{render_rt(rt)}
```

![adaptive degradation]({rt_svg.name})

The in-band classifier degrades from {1 - first.asr['input_only']:.0%} blocking to
{1 - last.asr['input_only']:.0%} in {len(rt.rounds)} rounds of surface-form
mutation. The out-of-band configuration holds flat at
{last.asr['out_of_band']:.0%} ASR across the same payloads, because its decision
does not read the payload's surface form at all — it reads where the argument
value came from and what the session has already done.

Running the same loop with the attacker adapting against `full` produces the same
curve, for a reason the harness states in its own output: a surface-form mutator
gets no fitness gradient from a layer that does not look at surface form. That is
a limit of this experiment, not a proof of robustness — see §4.

## 3. Where provenance stops working

```
{render_sweep(cells)}
```

![provenance sweep]({sweep_svg.name})

Each matcher rung buys exactly one class of obfuscation, and all of them fail at
level 6, where the destination never literally appears in the document. The block
rate stays flat because an unattributable control-plane argument is denied by
default — attribution is the *evidence*, the block is the *decision*, and they
come apart at the top of the ladder.

## 4. Limitations — read before quoting any number above

1. **The Layer-1 baseline is a stand-in.** `{guard.name}` is lexical and was
   written for this repo. Its weights were fixed before the corpus was run and
   were not tuned on it, but a trained guard model would sit at a different
   starting point. The *shape* of the degradation curve is the claim; the
   absolute round at which it crosses is not.
2. **The adaptive attacker only mutates surface form.** It may rephrase, encode
   and restructure the injected text, but not change the destination it is
   exfiltrating to — that destination is the attack's goal. An attacker whose
   goal address is itself allow-listed defeats provenance and the sanitizer, and
   is caught in this corpus only by the trajectory invariants (`atk-c3`,
   `atk-c4`).
3. **Provenance is reconstructed, not propagated.** Taint cannot follow a value
   through the model, so origin is inferred by matching. §3 measures exactly where
   that inference fails.
4. **The false positive is real and structural.** In `ben-a5` the user delegates
   the choice of recipient to a fetched page. The benign and attack versions are
   structurally identical — the destination genuinely originates in untrusted
   content in both — so provenance cannot separate them and blocks the legitimate
   one. This is the cost of the mechanism, not a tuning error.
5. **INV-5 never fires as the deciding layer** in this corpus. It is retained as
   defense in depth, and is reported as unexercised rather than presented as a
   contributing result.
6. **The agent is a deterministic scripted loop**, not a live model. That is
   deliberate — a varying planner would make a change in ASR unattributable to a
   change in the defense — but it means these numbers describe the *enforcement*
   layers, not an end-to-end system with a real planner in it.
7. **The corpus is small** ({len(scenarios)} scenarios, three attack families) and
   written by the same people who wrote the defense. It is a demonstration that
   the mechanisms behave as specified, not an independent benchmark.

## Artifacts

| file | contents |
|---|---|
| `runs/eval.json` | per-scenario results and metrics, every configuration |
| `runs/report.jsonl` | full audit log: every tag, sanitizer run, invariant check, decision |
| `runs/sweep.json` | obfuscation sweep cells |
| `runs/redteam_input_only.json`, `runs/redteam_full.json` | round-by-round red-team data |
| `runs/*.svg` | the two plots |
"""
    path = RUNS / "report.md"
    path.write_text(doc, encoding="utf-8")
    (RUNS / "eval.json").write_text(json.dumps({
        "metrics": [x.to_json() for x in metrics],
        "per_scenario": {n: [r.to_json() for r in rs.results] for n, rs in runs.items()},
    }, indent=2), encoding="utf-8")
    return path
